- hosts: all
  sudo: yes
  vars:
    - ntp_servers: 
        - 0.ubuntu.pool.ntp.org
        - 1.ubuntu.pool.ntp.org
        - 2.ubuntu.pool.ntp.org
    - package: ntp

  tasks:
    - name: Install NTP on Debian-like systems
      apt: name={{package}} state=installed update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: Set up ntp.conf
      template: src=ntp.conf.j2 dest=/etc/ntp.conf
      notify:
        - Restart NTP

  handlers:
    - name: Restart NTP
      service: name=ntp state=restarted
