- name: Per-user group creation
  group: name={{ item.value.username }} gid={{ item.value.uid }}
  with_dict: users
  when: users_create_per_user_group

- name: User creation
  user: name={{ item.value.username }}
        group={{ item.value.username if users_create_per_user_group else users_group }}
        groups={{ item.value.groups | join(',') }}
        shell={{ item.value.shell if item.value.shell is defined else users_default_shell }}
        comment="{{ item.key }}"
        uid={{ item.value.uid }}
        createhome={{ 'yes' if users_create_homedirs else 'no' }}
  with_dict: users

- name: SSH keys
  authorized_key: user={{ item.0.username }} key="{{ item.1 }}"
  with_subelements:
    - users
    - ssh_keys
